nome = str(input('qual o seu nome?')).strip()
print('analisando seu nome...')
print('seu nome em letras maiúsculas é: {}'.format(nome.upper()))
print('seu nome em letras minúsculas é: {}'.format(nome.lower()))
print('seu nome tem {} letras'.format(len(nome) - nome.count(' ')))
print('seu primeiro nome tem {} letras'.format(nome.find(' ')))